-- схема для пользователей
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- схема для вещей
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  request_id BIGINT,
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES public.users (id)
  -- CONSTRAINT fk_items_request FOREIGN KEY (request_id) REFERENCES public.item_requests (id)
);

-- схема для бронирования
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  CONSTRAINT pk_bookings PRIMARY KEY (id),
  CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES public.items (id),
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES public.users (id)
);