DROP TABLE IF EXISTS public.bookings CASCADE;

-- таблица для пользователей
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL,
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- таблица для вещей
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  request_id BIGINT,
  CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES public.users (id),
  CONSTRAINT fk_items_request FOREIGN KEY (request_id) REFERENCES public.item_requests (id)
);

-- таблица для бронирования
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES public.items (id),
  CONSTRAINT fk_bookings_booker FOREIGN KEY (booker_id) REFERENCES public.users(id)
);

-- таблица для отзывов
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  item_id BIGINT NOT NULL REFERENCES public.items(id),
  author_id BIGINT NOT NULL REFERENCES public.users(id),
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- таблица для запросов вещи
CREATE TABLE IF NOT EXISTS public.item_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  requester_id BIGINT NOT NULL,
  CONSTRAINT pk_item_requests PRIMARY KEY (id),
  CONSTRAINT fk_requests_user FOREIGN KEY (requester_id) REFERENCES public.users (id)
);